name: Generate Snake

on:
  schedule: # Run automatically every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: U-LF
          outputs: dist/snake.svg
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
